# Generated by Django 2.2.7 on 2019-11-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0002_auto_20191122_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Finished')], default=1),
            preserve_default=False,
        ),
    ]
