# Generated by Django 3.0.2 on 2020-01-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0005_auto_20191203_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
