# Generated by Django 3.0.2 on 2020-01-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0006_auto_20200111_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='endDate',
            field=models.DateTimeField(),
        ),
    ]
