# Generated by Django 3.0.2 on 2020-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0007_auto_20200111_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paymentSystem',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
