# Generated by Django 3.0.2 on 2020-01-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApi', '0009_auto_20200112_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='fatherName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='region',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
